version: "2"
linters:
  enable:
    - bidichk
    - bodyclose
    - durationcheck
    - errchkjson
    - errname
    - exptostd
    - forbidigo
    - goconst
    - gocritic
    - intrange
    - misspell
    - nestif
    - nilerr
    - perfsprint
    - reassign
    - revive
    - sloglint
    - tagalign
    - tagliatelle
    - tparallel
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - captLocal
    nestif:
      min-complexity: 7
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        - name: var-naming
        - name: receiver-naming
          disabled: true
    tagalign:
      align: false
      sort: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
